name: build

on:
  push:
  workflow_dispatch:

jobs:
  build-uefi-secureboot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: Project-Aloha/mu_aloha_platforms
          ref: main
          path: MU
      - name: Build UEFI (SB)
        run: |
          cd MU
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git submodule update --init --recursive
          docker build -t mu:v1 .
          docker run -v $(pwd):/build/ mu:v1 ./build_uefi.py -d xiaomi-nabu -s 1
          find . -type f -name 'SM8150_EFI.fd' -exec cp '{}' ../SM8150_EFI_SB.fd ';'
          find . -type f -name 'xiaomi-nabu.img' -exec cp '{}' ../uefi_secureboot.img ';'
      - uses: actions/upload-artifact@v4
        with:
          name: SM8150_EFI_SB.fd
          path: |
            SM8150_EFI_SB.fd
      - uses: actions/upload-artifact@v4
        with:
          name: uefi_secureboot.img
          path: |
            uefi_secureboot.img

  build-uefi-no-secureboot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: Project-Aloha/mu_aloha_platforms
          ref: main
          path: MU
      - name: Build UEFI (NOSB)
        run: |
          cd MU
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git submodule update --init --recursive
          docker build -t mu:v1 .
          docker run -v $(pwd):/build/ mu:v1 ./build_uefi.py -d xiaomi-nabu -s 0
          find . -type f -name 'SM8150_EFI.fd' -exec cp '{}' ../SM8150_EFI_NOSB.fd ';'
          find . -type f -name 'xiaomi-nabu.img' -exec cp '{}' ../uefi_no_secureboot.img ';'
      - uses: actions/upload-artifact@v4
        with:
          name: SM8150_EFI_NOSB.fd
          path: |
            SM8150_EFI_NOSB.fd
      - uses: actions/upload-artifact@v4
        with:
          name: uefi_no_secureboot.img
          path: |
            uefi_no_secureboot.img
  build-installer:
    needs: [build-uefi-secureboot,build-uefi-no-secureboot]
    strategy:
      matrix:
        uefi-type: [SB, NOSB]
    runs-on: ubuntu-latest
    steps:
      - id: time
        uses: boredland/get-time-action@2.0.0
        with:
          format: 'YYYYMMDD'
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/download-artifact@v4
        with:
          name: SM8150_EFI_${{ matrix.uefi-type }}.fd
      - name: Build Zip Installer (${{ matrix.uefi-type }})
        run: |
          mv SM8150_EFI_${{ matrix.uefi-type }}.fd Flashable_UEFI_Installer/SM8150_EFI.fd
          wget -nv "https://github.com/Project-Aloha/DualBootKernelPatcher/releases/download/v1.2.0.0/DualBootKernelPatcher-Linux-arm64.zip"
          unzip DualBootKernelPatcher-Linux-arm64.zip
          mv DualBootKernelPatcher Flashable_UEFI_Installer/DualBootKernelPatcher
          chmod +x Flashable_UEFI_Installer/DualBootKernelPatcher
          wget -nv "https://github.com/Project-Aloha/DualBootKernelPatcher/releases/download/v1.2.0.0/Shellcodes.zip"
          unzip Shellcodes.zip
          mv ShellCode.Nabu.bin Flashable_UEFI_Installer/ShellCode.Nabu.bin
          wget -nv "https://github.com/Project-Aloha/DualBootKernelPatcher/releases/download/v1.2.0.0/Config.zip"
          unzip Config.zip
          mv Config/DualBoot.Sm8150.cfg Flashable_UEFI_Installer/DualBoot.Sm8150.cfg
          chmod +x Flashable_UEFI_Installer/DualBootKernelPatcher
          cd Flashable_UEFI_Installer
          ./pack.sh
          mv installer.zip installer_${{ matrix.uefi-type }}.zip
      - uses: actions/upload-artifact@v4
        with:
          name: installer_${{ matrix.uefi-type }}.zip
          path: |
            Flashable_UEFI_Installer/installer_${{ matrix.uefi-type }}.zip
      - name: Release assets
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.time.outputs.time }}
          target_commitish: ${{ github.sha }}
          name: DualBoot UEFI Installer (${{ steps.time.outputs.time }})
          body_path: README.md
          draft: false
          prerelease: false
          files: |
            Flashable_UEFI_Installer/installer_${{ matrix.uefi-type }}.zip

